version: 2.1
orbs:
  slack: circleci/slack@0.1.0
  heroku: circleci/heroku@0.0.1
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello World
          command: |
            echo $food
            echo 'This is the delivery pipeline'
            
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Hello-World
